Apply new format to snippets and template
30-seconds/30-seconds-of-python pull request #229
Opened 2020-10-01 16:10 UTC by Arpit045-boop

2020-10-01 18:09 UTC, Trinityyi requested changes
Thanks for conributing. Please fix the mentioned issues and we can take another look afterwards.

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +tags: prime_number,intermediate
Tags should be `math,beginner`

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +Explain briefly what the snippet does.
Missing description

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +- Checks numbers from 2 to (given number - 1), If number is divisible by given numbers.
The explanation could use some more work. I suppose the algorithm is similar to the [JS implementation](https://www.30secondsofcode.org/js/s/is-prime), so you could write something similar?

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +def prime_number(number):
The complexity of this is sub-optimal. Also, I'm pretty sure the `else` part is incorrent. There's a better solution like the second to last snippet [here](https://stackoverflow.com/a/18833870/9298688).

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +prime_number(21) # result
The comment should show the result.

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +  # code
✂️ this comment please

2020-10-01 18:09 UTC, Trinityyi commented on snippets/prime_number.md
> +title: prime_number
Title should be `is_prime` with the function name matching that.

2020-10-02 09:30 UTC, Chalarangelo requested changes

2020-10-02 09:30 UTC, Chalarangelo commented on snippets/is_prime.md
> +
Please add a description.

2020-10-02 09:30 UTC, Chalarangelo commented on snippets/is_prime.md
> +        print("not a prime number")
Incorrect indentation.

2020-10-02 09:30 UTC, Chalarangelo commented on snippets/is_prime.md
> +        print("not a prime number")
The function must return a boolean value, not print the result.

2020-10-02 09:30 UTC, Chalarangelo commented on snippets/is_prime.md
> +  else:
The `else` is wrong. This should return after the loop is finished.

2020-10-02 09:30 UTC, Chalarangelo commented on snippets/is_prime.md
> +is_prime(21)
This should be followed by a comment with the result.

2020-10-02 12:27 UTC, Chalarangelo requested changes
> The complexity of this is sub-optimal. Also, I'm pretty sure the `else` part is incorrent. There's a better solution like the second to last snippet [here](https://stackoverflow.com/a/18833870/9298688).

The suggested implementation here looks significantly more performant, could you use that instead?

2020-10-03 14:00 UTC, Chalarangelo reviewed
Description, explanation and example are still wrong. Closing due to lack of following the guidelines and having to constantly review this over and over line by line.

2020-10-03 14:00 UTC, closed without merging